name: "CI"

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'media/**'
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'

  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'media/**'
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'
    types: [ opened, synchronize, reopened ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MONERO_DAEMON_URL: ${{ vars.DAEMON_URL }}
    strategy:
      fail-fast: false
      matrix:
        go-version: [ '1.20.x', '1.21.x', '1.x' ]

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install Dependencies 
        run: go mod download

      - name: Run Unit Tests
        run: go test ./test/unit

      - name: Change Resource Files Permission
        run: chmod -R a+rw ./test/integration/resources
      - name: Run Integration Tests
        run: go test ./test/integration
